### ISSUE TITLE
调试发现 构造函数Z最终返回的是Array 类型，不是类数组？不知道我的调试对不对

### ISSUE THREAD

**Issue by boylufeng20141007** [yeyuqiudeng/reading-zepto#3]
var h = $('h3'); Array.isArray(h) === true;

**Comment by HeftyKoo** [comment]
我试着调了一下，没有发现这个问题哦，可以给个在线demo吗?

**Comment by HeftyKoo** [comment]
看了一下 `v1.0` 的源码，`V1.0` 的 `$` 函数返回的确实是数组。你应该用的是 `v1.0` 。

其差别应该在 `Z` 函数的实现上。
`v1.0` 中是这样的 [https://github.com/madrobby/zepto/blob/v1.0/src/zepto.js#L134](https://github.com/madrobby/zepto/blob/v1.0/src/zepto.js#L134)
我看的 `1.2.0` 的源码中是这样的 [https://github.com/madrobby/zepto/blob/v1.2.0/src/zepto.js#L129](https://github.com/madrobby/zepto/blob/v1.2.0/src/zepto.js#L129)

`v1.0` 中直接调用函数，返回的 `dom` 是数组(注意`qsa` 中已经用 `slice` 将取得的节点转换成数组)。
`1.2.0` 中以构造函数方式调用，返回的类数组的 `constructor` 是zepto.Z。

**Comment by boylufeng20141007** [comment]
看了哈，是的。多谢。
