### ISSUE TITLE
在"源码内部方法"章节里面 likeArray

### ISSUE THREAD

**Issue by ClarenceC** [yeyuqiudeng/reading-zepto#4]
感觉在 type = $.type(obj) 这里 ,
把 $.type(obj)计算赋值出来,本地type调用是有好处的,避免函数内反复调用$.type()影响性能.
和for 里面的len感觉是一样
```javascript
for(var i = 0, len = array.lenght;i<len; i++) {
...
}
```
len 单独等出来,使每次循环的时候不用遍历数组计算长度.应该是一个道理啊.

**Comment by HeftyKoo** [comment]
@ClarenceC 有道理，谢谢

**Comment by ClarenceC** [comment]
向你学习,你写得很深入.
