### ISSUE TITLE
读Zepto源码之神奇的$的zepto.qsa中有错误，希望更正

### ISSUE THREAD

**Issue by Rudy24** [yeyuqiudeng/reading-zepto#5]
element.nodeType !== 1 && element.nodeType !== 9 && element.nodeType !== 11 。
1 对应的是 Node.ELEMENT_NODE ，10 对应的是 Node.DOCUMENT_TYPE_NODE ， 11 对应的是 Node.DOCUMENT_FRAGMENT_NODE ，如果不为以上三种类型，直接返回 []。

这里楼主写错了 10 对应的是 Node.DOCUMENT_TYPE_NODE, 应该是 9对应 着Node.DOCUMENT_NODE

**Comment by HeftyKoo** [comment]
谢谢指正
