### ISSUE TITLE
读Zepto方法之内部方法章节一处描述错误

### ISSUE THREAD

**Issue by Mcqueengit** [yeyuqiudeng/reading-zepto#7]
在**数据类型检测**——**isArray**处：
> 我们都知道，instanceof 的检测的原理是查找实例的 prototype 是否在构造函数的原型链上，如果在，则返回 true。

是不是应该修改为：
> 我们都知道，instanceof 的检测的原理是查找构造函数的 prototype 是否在实例的原型链上，如果在，则返回 true。

即 ```a instanceof b```，是查找 b.prototype 是否在 a 的原型链上。

**Comment by HeftyKoo** [comment]
你说得对，谢谢
